---
title: Heidi's Teriyaki Express
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: info@heidisteriyaki.com
description: |
  Authentic Asian Cuisine
baseurl: ''
url: ''
markdown: kramdown
permalink: pretty
