---
title: Heidi's Teriyaki Express
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: info@heidisteriyaki.com
description: |
  Vietnamese Phở Restaurant<br/>
  And Various Other<br/>
  Authentic Asian Cuisine
baseurl: ''
url: ''
markdown: kramdown
permalink: pretty

defaults:
- scope:
    type: posts
  values:
    layout: post
